name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.3
  flutter_bluetooth_serial: ^0.4.0
  sensors_plus: ^3.0.3
  cupertino_icons: ^1.0.8
  google_sign_in: ^5.4.2
  firebase_auth: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
