name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^5.4.2
  firebase_auth: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/vr_golf_logo.png
    - assets/images/google_icon.png
    - assets/images/create_room.png
    - assets/images/join_room.png
    - assets/images/avatar_setting.png
    - assets/images/game_setting.png
    - assets/images/help.png


