// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL29QuiEH7tOQaC7jC8yu9d_XYqnRMvtU',
    appId: '1:407181091525:web:845a2afc761ffd303e46ac',
    messagingSenderId: '407181091525',
    projectId: 'vr-golf-98c10',
    authDomain: 'vr-golf-98c10.firebaseapp.com',
    storageBucket: 'vr-golf-98c10.firebasestorage.app',
    measurementId: 'G-EJQLVX4HRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGxvwGzo9_iC5_m-B68_eK2Fieet0IdSE',
    appId: '1:974153956306:android:332b0457c050bd3158260b',
    messagingSenderId: '974153956306',
    projectId: 'vr-golf-game',
    storageBucket: 'vr-golf-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPFW7iTaooGfMHFFR_m8zU6TlTGDiX_-o',
    appId: '1:974153956306:ios:7a8a2a83d065819658260b',
    messagingSenderId: '974153956306',
    projectId: 'vr-golf-game',
    storageBucket: 'vr-golf-game.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxUekEL24vQs7lR4vkm_9sYqpkih94fOs',
    appId: '1:407181091525:ios:4921c76d15cda17f3e46ac',
    messagingSenderId: '407181091525',
    projectId: 'vr-golf-98c10',
    storageBucket: 'vr-golf-98c10.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhaMdgrRofzqm-GB3-uH_JkxRZBB_rYXo',
    appId: '1:974153956306:web:9a6eb15fbef06f0a58260b',
    messagingSenderId: '974153956306',
    projectId: 'vr-golf-game',
    authDomain: 'vr-golf-game.firebaseapp.com',
    storageBucket: 'vr-golf-game.firebasestorage.app',
  );

}